# Generated by Django 5.2.6 on 2026-08-14 05:46

import django.db.models.deletion
import django.utils.timezone
import social.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='like',
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.RenameField(
            model_name='channelmessage',
            old_name='channemessage_id',
            new_name='channelmessage_id',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='pictureUrl',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='channel',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_of_channel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_from_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_broadcast_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_file'),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='link_preview',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social.channelmessage'),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='link_preview',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='linked_job_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='linked_product_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social.message'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='social.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='enabled_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_type',
            field=models.CharField(blank=True, choices=[('skilled_professional', 'Skilled Professional'), ('job_seeker', 'Job Seeker'), ('business_owner', 'Business Owner'), ('teacher_tutor', 'Teacher / Tutor'), ('freelancer', 'Freelancer'), ('artisan_technician', 'Artisan / Technician'), ('service_provider', 'Service Provider'), ('student_apprentice', 'Student / Apprentice'), ('employer_recruiter', 'Employer / Recruiter'), ('other_professional', 'Other Professional')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_type_cv',
            field=models.FileField(blank=True, null=True, upload_to='member_type/cv/', validators=[social.models.validate_cv_extension]),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_type_cv_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_type_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Everyone'), ('followers_only', 'Followers only'), ('private', 'Nobody (Hidden)')], db_index=True, default='public', help_text='Controls who can view this profile details', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='sells_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_dob',
            field=models.BooleanField(default=False, help_text='Show date of birth on public profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_gender',
            field=models.BooleanField(default=True, help_text='Show gender on public profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='subscribed_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to='social.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPage',
            fields=[
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('retail', 'Retail & Shopping'), ('food', 'Food & Beverage'), ('fashion', 'Fashion & Apparel'), ('electronics', 'Electronics & Tech'), ('beauty', 'Beauty & Wellness'), ('education', 'Education & Training'), ('services', 'Professional Services'), ('agriculture', 'Agriculture & Farming'), ('real_estate', 'Real Estate & Property'), ('logistics', 'Logistics & Delivery'), ('auto', 'Automobiles & Vehicles'), ('others', 'Others')], default='others', max_length=30)),
                ('page_type', models.CharField(choices=[('business', 'Business Owner'), ('freelancer', 'Freelancer'), ('developer', 'Developer / Tech Professional'), ('teacher', 'Teacher / Tutor'), ('artisan', 'Artisan / Technician'), ('service_provider', 'Service Provider'), ('creative', 'Creative / Artist'), ('student', 'Student'), ('skilled_professional', 'Skilled Professional'), ('other', 'Other Professional')], db_index=True, default='business', max_length=25)),
                ('sells_products', models.BooleanField(default=True)),
                ('enabled_sections', models.JSONField(blank=True, default=list)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('instagram', models.CharField(blank=True, default='', help_text='Username or @handle', max_length=100)),
                ('youtube', models.URLField(blank=True, default='', help_text='Full channel URL', max_length=300)),
                ('facebook', models.URLField(blank=True, default='', help_text='Full page URL', max_length=300)),
                ('twitter', models.CharField(blank=True, default='', help_text='Username or @handle', max_length=100)),
                ('tiktok', models.CharField(blank=True, default='', help_text='Username or @handle', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Per-day opening hours, e.g. {"mon": {"open": "09:00", "close": "18:00", "closed": false}}')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='business_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_business_pages', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BusinessPage_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAchievement',
            fields=[
                ('achievement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('issuer', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('date_achieved', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_achievement_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='social.businesspage')),
            ],
            options={
                'db_table': 'BusinessAchievement_Table',
                'ordering': ['order', '-date_achieved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPortfolioItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('portfolio', 'Portfolio piece'), ('project', 'Project')], db_index=True, default='portfolio', max_length=12)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('link_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_ongoing', models.BooleanField(default=False, help_text='Only meaningful for projects.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_portfolio_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='social.businesspage')),
            ],
            options={
                'db_table': 'BusinessPortfolioItem_Table',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPost',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text update'), ('poll', 'Poll')], db_index=True, default='text', max_length=10)),
                ('post_category', models.CharField(choices=[('update', 'General Update'), ('work', 'Work Update'), ('project', 'Project'), ('tutorial', 'Tutorial'), ('announcement', 'Announcement')], db_index=True, default='update', max_length=15)),
                ('caption', models.TextField(blank=True, default='')),
                ('video', models.FileField(blank=True, null=True, upload_to='business_post_videos/')),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.businesspage')),
            ],
            options={
                'db_table': 'BusinessPost_Table',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.businesspost')),
            ],
            options={
                'db_table': 'BusinessPostComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPostImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.businesspost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPostPoll',
            fields=[
                ('poll_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Let voters pick more than one option.')),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='social.businesspost')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPostPollOption',
            fields=[
                ('option_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='social.businesspostpoll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPostPollVote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.businesspostpolloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPostVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.businesspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_post_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BusinessPostVibe_Table',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('price_text', models.CharField(blank=True, default='', help_text='e.g. ₦15,000, Starting from ₦5,000/hr, or Negotiable', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_service_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='social.businesspage')),
            ],
            options={
                'db_table': 'BusinessService_Table',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Wow'), ('😢', 'Sad'), ('😡', 'Angry'), ('👍', 'Thumbs Up'), ('🔥', 'Fire'), ('🎉', 'Party')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.channelmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelUserLastSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_notifications', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_follow_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('gig', 'Gig'), ('fulltime', 'Full-time'), ('apprenticeship', 'Apprenticeship')], db_index=True, default='fulltime', max_length=20)),
                ('work_mode', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, default='on_site', help_text='Where the work happens — On-site, Remote, or Hybrid (like LinkedIn)', max_length=20)),
                ('advertiser_type', models.CharField(choices=[('personal', 'Personal'), ('company_school', 'Company / School'), ('government', 'Government')], db_index=True, default='personal', help_text='Who is behind this vacancy — helps applicants judge how official it is', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, default='')),
                ('contact_info', models.CharField(blank=True, default='', help_text='Email, phone, or link to apply', max_length=300)),
                ('apply_link', models.URLField(blank=True, default='', help_text='Optional external link — official portal, application form, etc.', max_length=500)),
                ('salary_range', models.CharField(blank=True, default='', help_text='e.g. ₦80,000–₦120,000/month or "Negotiable"', max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='job_covers/')),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_vacancies', to='social.businesspage')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'JobVacancy_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_comments', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.jobvacancy')),
            ],
            options={
                'db_table': 'JobComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='linked_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_messages', to='social.jobvacancy'),
        ),
        migrations.CreateModel(
            name='JobVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.jobvacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'JobVibe_Table',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=254)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('succeeded', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LoginAttempt_Table',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['username', 'attempted_at'], name='login_attempt_user_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_location', models.CharField(max_length=300)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_availability', models.CharField(max_length=150)),
                ('product_condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used - Like New'), ('Fair', 'Used - Fair Condition')], default='New', max_length=50)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_promoted', models.BooleanField(default=False)),
                ('product_category', models.CharField(choices=[('phones', 'Phones & Tablets'), ('computers', 'Computers & Laptops'), ('electronics', 'Electronics & Gadgets'), ('accessories', 'Phone Accessories'), ('tv_audio', 'TVs & Audio'), ('cameras', 'Cameras & Photography'), ('gaming', 'Gaming'), ('fashion_men', "Men's Fashion"), ('fashion_women', "Women's Fashion"), ('fashion_kids', "Kids' Fashion"), ('watches', 'Watches & Jewelry'), ('shoes', 'Shoes & Sneakers'), ('bags', 'Bags & Luggage'), ('home_appliances', 'Home Appliances'), ('furniture', 'Furniture & Décor'), ('kitchen', 'Kitchen & Dining'), ('garden', 'Garden & Outdoor'), ('beauty', 'Beauty & Skincare'), ('health', 'Health & Wellness'), ('food', 'Food & Groceries'), ('drinks', 'Drinks & Beverages'), ('vehicles', 'Vehicles & Parts'), ('properties', 'Properties & Real Estate'), ('office', 'Office & Stationery'), ('agriculture', 'Agriculture & Farming'), ('services', 'Services & Gigs'), ('sports', 'Sports & Fitness'), ('books', 'Books & Education'), ('toys', 'Toys & Baby Items'), ('others', 'Others')], db_index=True, default='others', max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('ad_url', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('business_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_listings', to='social.businesspage')),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('new_follower', 'New page follower'), ('new_product', 'New product'), ('new_comment', 'New comment on a post')], db_index=True, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_business_notifications', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_notifications', to=settings.AUTH_USER_MODEL)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.businesspage')),
                ('post', models.ForeignKey(blank=True, help_text='Set for new_comment notifications only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='social.businesspost')),
                ('product', models.ForeignKey(blank=True, help_text='Set for new_product notifications only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_product_notifications', to='social.market')),
            ],
            options={
                'db_table': 'BusinessNotification_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_messages', to='social.market'),
        ),
        migrations.CreateModel(
            name='MarketImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.market')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Wow'), ('😢', 'Sad'), ('😡', 'Angry'), ('👍', 'Thumbs Up'), ('🔥', 'Fire'), ('🎉', 'Party')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 – Poor'), (2, '2 – Fair'), (3, '3 – Good'), (4, '4 – Very Good'), (5, '5 – Excellent')])),
                ('comment', models.TextField(blank=True, default='', max_length=2000)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='social.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProductReview_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileAchievement',
            fields=[
                ('achievement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('issuer', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('date_achieved', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_achievement_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='social.profile')),
            ],
            options={
                'db_table': 'ProfileAchievement_Table',
                'ordering': ['order', '-date_achieved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePortfolioItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('portfolio', 'Portfolio piece'), ('project', 'Project')], db_index=True, default='portfolio', max_length=12)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('link_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_ongoing', models.BooleanField(default=False, help_text='Only meaningful for projects.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_portfolio_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='social.profile')),
            ],
            options={
                'db_table': 'ProfilePortfolioItem_Table',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePost',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text update'), ('poll', 'Poll')], db_index=True, default='text', max_length=10)),
                ('post_category', models.CharField(choices=[('update', 'General Update'), ('work', 'Work Update'), ('project', 'Project'), ('tutorial', 'Tutorial'), ('announcement', 'Announcement')], db_index=True, default='update', max_length=15)),
                ('caption', models.TextField(blank=True, default='')),
                ('video', models.FileField(blank=True, null=True, upload_to='profile_post_videos/')),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_posts', to='social.profile')),
            ],
            options={
                'db_table': 'ProfilePost_Table',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.profilepost')),
            ],
            options={
                'db_table': 'ProfilePostComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePostImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.profilepost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePostPoll',
            fields=[
                ('poll_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Let voters pick more than one option.')),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='social.profilepost')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePostPollOption',
            fields=[
                ('option_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='social.profilepostpoll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePostPollVote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.profilepostpolloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePostVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.profilepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_post_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfilePostVibe_Table',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('price_text', models.CharField(blank=True, default='', help_text='e.g. ₦15,000, Starting from ₦5,000/hr, or Negotiable', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_service_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='social.profile')),
            ],
            options={
                'db_table': 'ProfileService_Table',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('school', 'What primary school did you attend?'), ('city', 'In what city were you born?'), ('mother', "What is your mother's maiden name?"), ('friend', 'What is the name of your childhood best friend?'), ('car', 'What was the make of your first car?'), ('street', 'What street did you grow up on?'), ('nickname', 'What nickname did your family call you as a child?')], max_length=20)),
                ('answer_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secret_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SecretQuestion_Table',
            },
        ),
        migrations.CreateModel(
            name='SocialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('town', 'Town Meeting'), ('festival', 'Festival'), ('wedding', 'Wedding'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('networking', 'Networking'), ('meetup', 'Meetup'), ('seminar', 'Seminar'), ('training', 'Training / Class'), ('concert', 'Concert / Live Music'), ('sports', 'Sports'), ('exhibition', 'Exhibition / Expo'), ('charity', 'Charity / Fundraiser'), ('party', 'Party / Social'), ('reunion', 'Reunion'), ('religious', 'Religious / Faith'), ('product_launch', 'Product Launch'), ('sale', 'Sale / Promo'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional — for multi-day events', null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('organizer_name', models.CharField(blank=True, default='', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_virtual', models.BooleanField(db_index=True, default=False)),
                ('virtual_link', models.URLField(blank=True, default='', max_length=500)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited spots', null=True)),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SocialEvent_Table',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='EventVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_vibes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.socialevent')),
            ],
            options={
                'db_table': 'EventVibe_Table',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('event_updated', 'Event updated'), ('event_reminder', 'Event reminder'), ('event_cancelled', 'Event cancelled'), ('new_comment', 'New comment')], db_index=True, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_notifications', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.socialevent')),
            ],
            options={
                'db_table': 'EventNotification_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('going', 'Going')], default='interested', max_length=12)),
                ('notify', models.BooleanField(default=True, help_text='Receive notifications about this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_events', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='social.socialevent')),
            ],
            options={
                'db_table': 'EventFollow_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.socialevent')),
            ],
            options={
                'db_table': 'EventComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or fake account'), ('harassment', 'Harassment or bullying'), ('hate_speech', 'Hate speech or discrimination'), ('inappropriate', 'Inappropriate content'), ('impersonation', 'Impersonation'), ('other', 'Something else')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserReport_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='social.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Wishlist_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocker'], name='blockeduser_blocker_idx'),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocked'], name='blockeduser_blocked_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AddConstraint(
            model_name='businesspostpollvote',
            constraint=models.UniqueConstraint(fields=('option', 'user'), name='unique_vote_per_option_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='businesspostvibe',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='channelmessagereaction',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='channeluserlastseen',
            unique_together={('channel', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='follownotification',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AlterUniqueTogether(
            name='jobvibe',
            unique_together={('job', 'user')},
        ),
        migrations.AddIndex(
            model_name='businessnotification',
            index=models.Index(fields=['to_user', 'is_read'], name='BusinessNot_to_user_6b4fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnotification',
            index=models.Index(fields=['business_page', 'notif_type'], name='BusinessNot_busines_3ce285_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', '-created_at'], name='review_product_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
        migrations.AddConstraint(
            model_name='profilepostpollvote',
            constraint=models.UniqueConstraint(fields=('option', 'user'), name='unique_vote_per_option_per_user_profile'),
        ),
        migrations.AlterUniqueTogether(
            name='profilepostvibe',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventvibe',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='eventnotification',
            index=models.Index(fields=['to_user', 'is_read'], name='EventNotifi_to_user_751b13_idx'),
        ),
        migrations.AddIndex(
            model_name='eventnotification',
            index=models.Index(fields=['event', 'notif_type'], name='EventNotifi_event_i_b2890d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventfollow',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userreport',
            unique_together={('reporter', 'reported', 'reason')},
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'created_at'], name='wishlist_user_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
