# Generated by Django 5.2.6 on 2025-11-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='post_file'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='file',
            field=models.FileField(blank=True, upload_to='comment_file'),
        ),
    ]
