# Generated by Django 5.2.6 on 2025-11-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_file_alter_postcomment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
