# Generated by Django 5.2.6 on 2026-08-15 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_post_author_remove_post_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnotification',
            name='vibe_type',
            field=models.CharField(blank=True, default='', help_text='Set for new_vibe notifications only (e.g. "fire", "love").', max_length=10),
        ),
        migrations.AlterField(
            model_name='businessnotification',
            name='notif_type',
            field=models.CharField(choices=[('new_follower', 'New page follower'), ('new_product', 'New product'), ('new_comment', 'New comment on a post'), ('new_vibe', 'New reaction on a post')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='businessnotification',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Set for new_comment / new_vibe notifications only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='social.businesspost'),
        ),
        migrations.CreateModel(
            name='ProfilePostNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('new_vibe', 'New reaction'), ('new_comment', 'New comment')], db_index=True, max_length=20)),
                ('vibe_type', models.CharField(blank=True, default='', help_text='Set for new_vibe notifications only (e.g. "fire", "love").', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_profile_post_notifications', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, help_text='Set for new_comment notifications only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.profilepostcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.profilepost')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_post_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfilePostNotification_Table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'is_read'], name='ProfilePost_to_user_afef49_idx'), models.Index(fields=['post', 'notif_type'], name='ProfilePost_post_id_c5d714_idx')],
            },
        ),
    ]
