# Generated by Django 5.2.6 on 2026-06-26 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_post_author_remove_post_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPage',
            fields=[
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('retail', 'Retail & Shopping'), ('food', 'Food & Beverage'), ('fashion', 'Fashion & Apparel'), ('electronics', 'Electronics & Tech'), ('beauty', 'Beauty & Wellness'), ('education', 'Education & Training'), ('services', 'Professional Services'), ('agriculture', 'Agriculture & Farming'), ('real_estate', 'Real Estate & Property'), ('logistics', 'Logistics & Delivery'), ('auto', 'Automobiles & Vehicles'), ('others', 'Others')], default='others', max_length=30)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='business_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_business_pages', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BusinessPage_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProduct',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('used', 'Used – Like New'), ('used_fair', 'Used – Fair Condition')], default='new', max_length=20)),
                ('availability', models.CharField(choices=[('single', 'Single Item'), ('in_stock', 'In Stock')], default='in_stock', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_products', to='social.businesspage')),
            ],
            options={
                'db_table': 'BusinessProduct_Table',
                'ordering': ['-posted_on'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProductImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='business_product_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.businessproduct')),
            ],
            options={
                'db_table': 'BusinessProductImage_Table',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
