# Generated by Django 5.2.6 on 2026-06-27 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_businesspage_businessproduct_businessproductimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessproductimage',
            name='product',
        ),
        migrations.AddField(
            model_name='market',
            name='business_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_listings', to='social.businesspage'),
        ),
        migrations.DeleteModel(
            name='BusinessProduct',
        ),
        migrations.DeleteModel(
            name='BusinessProductImage',
        ),
    ]
