# Generated by Django 5.2.6 on 2025-11-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_profile_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to='comment_file'),
        ),
    ]
