# Generated by Django 5.2.6 on 2026-08-17 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_businessnotification_vibe_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('education_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=150)),
                ('degree', models.CharField(blank=True, default='', max_length=150)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=150)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_education_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='social.profile')),
            ],
            options={
                'db_table': 'ProfileEducation_Table',
                'ordering': ['order', '-is_current', '-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileExperience',
            fields=[
                ('experience_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Role / position, e.g. Software Engineer Intern', max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('volunteer', 'Volunteer')], default='', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_experience_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='social.profile')),
            ],
            options={
                'db_table': 'ProfileExperience_Table',
                'ordering': ['order', '-is_current', '-start_date', '-created_at'],
            },
        ),
    ]
