# Generated by Django 5.2.6 on 2026-06-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_businessproductimage_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketvibe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='marketvibe',
            name='product',
        ),
        migrations.RemoveField(
            model_name='marketvibe',
            name='user',
        ),
        migrations.DeleteModel(
            name='MarketComment',
        ),
        migrations.DeleteModel(
            name='MarketVibe',
        ),
    ]
