# Generated by Django 5.2.6 on 2026-08-18 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_profileeducation_profileexperience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAchievementComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.profileachievement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_achievement_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfileAchievementComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileEducationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_education_comments', to=settings.AUTH_USER_MODEL)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.profileeducation')),
            ],
            options={
                'db_table': 'ProfileEducationComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileExperienceComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_experience_comments', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.profileexperience')),
            ],
            options={
                'db_table': 'ProfileExperienceComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePortfolioItemComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_portfolio_comments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.profileportfolioitem')),
            ],
            options={
                'db_table': 'ProfilePortfolioItemComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileServiceComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_service_comments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.profileservice')),
            ],
            options={
                'db_table': 'ProfileServiceComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileAchievementVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.profileachievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_achievement_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfileAchievementVibe_Table',
                'ordering': ['created_at'],
                'unique_together': {('achievement', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProfileEducationVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.profileeducation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_education_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfileEducationVibe_Table',
                'ordering': ['created_at'],
                'unique_together': {('education', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProfileExperienceVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.profileexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_experience_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfileExperienceVibe_Table',
                'ordering': ['created_at'],
                'unique_together': {('experience', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProfilePortfolioItemVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.profileportfolioitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_portfolio_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfilePortfolioItemVibe_Table',
                'ordering': ['created_at'],
                'unique_together': {('item', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProfileServiceVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.profileservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_service_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfileServiceVibe_Table',
                'ordering': ['created_at'],
                'unique_together': {('service', 'user')},
            },
        ),
    ]
