# Generated by Django 5.2.6 on 2026-06-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_marketvibe_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspage',
            name='facebook',
            field=models.URLField(blank=True, default='', help_text='Full page URL', max_length=300),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='instagram',
            field=models.CharField(blank=True, default='', help_text='Username or @handle', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='tiktok',
            field=models.CharField(blank=True, default='', help_text='Username or @handle', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text='Username or @handle', max_length=100),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='youtube',
            field=models.URLField(blank=True, default='', help_text='Full channel URL', max_length=300),
        ),
    ]
