# Generated by Django 5.2.6 on 2026-08-19 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_profileachievementcomment_profileeducationcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileItemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('new_vibe', 'New reaction'), ('new_comment', 'New comment')], db_index=True, max_length=20)),
                ('section', models.CharField(choices=[('portfolio', 'Portfolio / Project'), ('achievement', 'Achievement'), ('experience', 'Experience'), ('education', 'Education'), ('service', 'Service')], db_index=True, max_length=20)),
                ('vibe_type', models.CharField(blank=True, default='', help_text='Set for new_vibe notifications only (e.g. "fire", "love").', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.profileachievement')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_profile_item_notifications', to=settings.AUTH_USER_MODEL)),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.profileeducation')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.profileexperience')),
                ('portfolio_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.profileportfolioitem')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.profileservice')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_item_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfileItemNotification_Table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'is_read'], name='ProfileItem_to_user_39dd7b_idx'), models.Index(fields=['section', 'notif_type'], name='ProfileItem_section_50677a_idx')],
            },
        ),
    ]
