# Generated by Django 5.2.6 on 2026-06-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_businesspage_facebook_businesspage_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='product_category',
            field=models.CharField(choices=[('phones', 'Phones & Tablets'), ('computers', 'Computers & Laptops'), ('electronics', 'Electronics & Gadgets'), ('accessories', 'Phone Accessories'), ('tv_audio', 'TVs & Audio'), ('cameras', 'Cameras & Photography'), ('gaming', 'Gaming'), ('fashion_men', "Men's Fashion"), ('fashion_women', "Women's Fashion"), ('fashion_kids', "Kids' Fashion"), ('watches', 'Watches & Jewelry'), ('shoes', 'Shoes & Sneakers'), ('bags', 'Bags & Luggage'), ('home_appliances', 'Home Appliances'), ('furniture', 'Furniture & Décor'), ('kitchen', 'Kitchen & Dining'), ('garden', 'Garden & Outdoor'), ('beauty', 'Beauty & Skincare'), ('health', 'Health & Wellness'), ('food', 'Food & Groceries'), ('drinks', 'Drinks & Beverages'), ('vehicles', 'Vehicles & Parts'), ('properties', 'Properties & Real Estate'), ('office', 'Office & Stationery'), ('agriculture', 'Agriculture & Farming'), ('services', 'Services & Gigs'), ('sports', 'Sports & Fitness'), ('books', 'Books & Education'), ('toys', 'Toys & Baby Items'), ('others', 'Others')], db_index=True, default='others', max_length=100),
        ),
    ]
