# Generated by Django 5.2.6 on 2026-08-21 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_profileitemnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPortfolioImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_portfolio_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='social.businessportfolioitem')),
            ],
            options={
                'db_table': 'BusinessPortfolioImage_Table',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 – Poor'), (2, '2 – Fair'), (3, '3 – Good'), (4, '4 – Very Good'), (5, '5 – Excellent')])),
                ('comment', models.TextField(blank=True, default='', max_length=2000)),
                ('is_edited', models.BooleanField(default=False)),
                ('owner_reply', models.TextField(blank=True, default='', max_length=2000)),
                ('owner_reply_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='social.businesspage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_page_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BusinessReview_Table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_page', '-created_at'], name='bizreview_page_time_idx')],
                'unique_together': {('business_page', 'user')},
            },
        ),
    ]
