# Generated by Django 5.2.6 on 2025-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_profile_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, upload_to='post_file'),
        ),
    ]
