# Generated by Django 5.2.6 on 2026-08-23 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_businessportfolioimage_businessreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=20)),
                ('cover_letter', models.TextField()),
                ('portfolio_link', models.URLField(blank=True, default='', max_length=500)),
                ('additional_message', models.TextField(blank=True, default='')),
                ('resume', models.FileField(blank=True, null=True, upload_to='job_applications/resumes/')),
                ('resume_name', models.CharField(blank=True, default='', max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='social.jobvacancy')),
            ],
            options={
                'db_table': 'JobApplication_Table',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('applied', 'New application'), ('status_changed', 'Application status changed'), ('withdrawn', 'Application withdrawn')], db_index=True, max_length=20)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_job_application_notifications', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.jobapplication')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'JobApplicationNotification_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='JobApplicat_job_id_bdba63_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status'], name='JobApplicat_applica_c737bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'applicant')},
        ),
        migrations.AddIndex(
            model_name='jobapplicationnotification',
            index=models.Index(fields=['to_user', 'is_read'], name='JobApplicat_to_user_17aa84_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplicationnotification',
            index=models.Index(fields=['application', 'notif_type'], name='JobApplicat_applica_bad4de_idx'),
        ),
    ]
