# Generated by Django 5.2.6 on 2026-06-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_market_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='community_area',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='family_house',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='residency_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secondary_school',
        ),
    ]
