# Generated by Django 5.2.6 on 2026-08-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_jobapplication_jobapplicationnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
