# Generated by Django 5.2.6 on 2025-11-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_market_marketimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.market'),
        ),
    ]
