# Generated by Django 5.2.6 on 2026-07-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='business_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_vacancies', to='social.businesspage'),
        ),
    ]
