# Generated by Django 5.2.6 on 2026-07-14 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_jobvacancy_business_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('new_follower', 'New page follower'), ('new_product', 'New product')], db_index=True, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_business_notifications', to=settings.AUTH_USER_MODEL)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.businesspage')),
                ('product', models.ForeignKey(blank=True, help_text='Set for new_product notifications only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_product_notifications', to='social.market')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BusinessNotification_Table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'is_read'], name='BusinessNot_to_user_6b4fc2_idx'), models.Index(fields=['business_page', 'notif_type'], name='BusinessNot_busines_3ce285_idx')],
            },
        ),
    ]
