# Generated by Django 5.2.6 on 2026-08-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_profile_looking_for_alter_businessachievement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessachievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_achievement_images/'),
        ),
        migrations.AlterField(
            model_name='businesspage',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='business_covers/'),
        ),
        migrations.AlterField(
            model_name='businesspage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AlterField(
            model_name='businessportfolioimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='businessportfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='businesspost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='business_post_videos/'),
        ),
        migrations.AlterField(
            model_name='businesspostimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_post_images/'),
        ),
        migrations.AlterField(
            model_name='businessservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_service_images/'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_file'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='job_applications/resumes/'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_covers/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='male.png', upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='profileachievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_achievement_images/'),
        ),
        migrations.AlterField(
            model_name='profileeducation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_education_images/'),
        ),
        migrations.AlterField(
            model_name='profileexperience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_experience_images/'),
        ),
        migrations.AlterField(
            model_name='profileportfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='profilepost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='profile_post_videos/'),
        ),
        migrations.AlterField(
            model_name='profilepostimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_post_images/'),
        ),
        migrations.AlterField(
            model_name='profileservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_service_images/'),
        ),
        migrations.AlterField(
            model_name='socialevent',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/'),
        ),
    ]
