# Generated by Django 5.2.6 on 2025-11-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_marketimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='product_Location',
            new_name='product_location',
        ),
    ]
