# Generated by Django 5.2.6 on 2026-07-18 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_businessnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 – Poor'), (2, '2 – Fair'), (3, '3 – Good'), (4, '4 – Very Good'), (5, '5 – Excellent')])),
                ('comment', models.TextField(blank=True, default='', max_length=2000)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='social.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProductReview_Table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='review_product_time_idx')],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
