# Generated by Django 5.2.6 on 2025-12-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_rename_product_location_market_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmessage',
            name='image',
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='channel_files/'),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
