# Generated by Django 5.2.6 on 2026-08-26 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_businessachievement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='required_documents',
            field=models.CharField(blank=True, default='', help_text='Comma-separated codes for the specific results/certificates this poster wants applicants to attach (e.g. "waec,neco,degree_certificate"). Valid codes come from JOB_DOCUMENT_TYPE_CHOICES.', max_length=255),
        ),
        migrations.CreateModel(
            name='JobApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('waec', 'WAEC Result'), ('neco', 'NECO Result'), ('nabteb', 'NABTEB Result'), ('degree_certificate', 'Degree Certificate'), ('hnd_nd_certificate', 'HND / ND Certificate'), ('nysc_certificate', 'NYSC Certificate'), ('birth_certificate', 'Birth Certificate'), ('international_passport', 'International Passport'), ('other', 'Other Certificate / Document')], max_length=30)),
                ('doc_label', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='job_applications/documents/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='social.jobapplication')),
            ],
            options={
                'db_table': 'JobApplicationDocument_Table',
                'ordering': ['doc_type', 'uploaded_at'],
            },
        ),
    ]
