# Generated by Django 5.2.6 on 2025-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_remove_channelmessage_image_channelmessage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='channel_files'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
