# Generated by Django 5.2.6 on 2026-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspage',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Per-day opening hours, e.g. {"mon": {"open": "09:00", "close": "18:00", "closed": false}}'),
        ),
    ]
