# Generated by Django 5.2.6 on 2026-08-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_businesspage_bizpage_active_cat_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspage',
            old_name='tiktok',
            new_name='telegram',
        ),
        migrations.RemoveField(
            model_name='businesspage',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='businesspage',
            name='enabled_sections',
        ),
        migrations.RemoveField(
            model_name='businesspage',
            name='page_type',
        ),
        migrations.AddField(
            model_name='businesspage',
            name='close_time',
            field=models.CharField(blank=True, default='18:00', max_length=10),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='is_24hrs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='open_time',
            field=models.CharField(blank=True, default='09:00', max_length=10),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='Cash, Transfer, POS, etc.'),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='pickup_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='registration_number',
            field=models.CharField(blank=True, default='', help_text='RC Number or BN', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesspage',
            name='category',
            field=models.CharField(choices=[('retail', 'Retail & Shopping'), ('food', 'Food & Beverage'), ('fashion', 'Fashion & Apparel'), ('electronics', 'Electronics & Tech'), ('beauty', 'Beauty & Wellness'), ('services', 'Professional Services'), ('agriculture', 'Agriculture & Farming'), ('logistics', 'Logistics & Delivery'), ('education', 'Education & Training'), ('others', 'Others')], default='others', max_length=30),
        ),
    ]
