# Generated by Django 5.2.6 on 2025-12-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_channelmessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
