# Generated by Django 5.2.6 on 2026-07-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_businesspage_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='linked_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_messages', to='social.jobvacancy'),
        ),
        migrations.AddField(
            model_name='message',
            name='linked_job_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
