# Generated by Django 5.2.6 on 2025-12-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_channelmessage_file_url_alter_channelmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='pictureUrl',
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
