# Generated by Django 5.2.6 on 2026-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_message_linked_job_message_linked_job_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='advertiser_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('company_school', 'Company / School'), ('government', 'Government')], db_index=True, default='personal', help_text='Who is behind this vacancy — helps applicants judge how official it is', max_length=20),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='apply_link',
            field=models.URLField(blank=True, default='', help_text='Optional external link — official portal, application form, etc.', max_length=500),
        ),
    ]
