# Generated by Django 5.2.6 on 2026-08-28 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_rename_tiktok_businesspage_telegram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='channelmessage',
            index=models.Index(fields=['channel', '-created_at'], name='chanmsg_channel_created_idx'),
        ),
    ]
