# Generated by Django 5.2.6 on 2026-08-29 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_channelmessage_chanmsg_channel_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspage',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_business_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
