# Generated by Django 5.2.6 on 2025-12-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_remove_channelmessage_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmessage',
            old_name='file_url',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='file_name',
        ),
    ]
