# Generated by Django 5.2.6 on 2026-07-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_jobvacancy_advertiser_type_jobvacancy_apply_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='work_mode',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, default='on_site', help_text='Where the work happens — On-site, Remote, or Hybrid (like LinkedIn)', max_length=20),
        ),
    ]
