# Generated by Django 5.2.6 on 2026-08-01 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_jobvacancy_work_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialevent',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited spots', null=True),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional — for multi-day events', null=True),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='is_virtual',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='organizer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='virtual_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='socialevent',
            name='event_type',
            field=models.CharField(choices=[('town', 'Town Meeting'), ('festival', 'Festival'), ('wedding', 'Wedding'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('networking', 'Networking'), ('meetup', 'Meetup'), ('seminar', 'Seminar'), ('training', 'Training / Class'), ('concert', 'Concert / Live Music'), ('sports', 'Sports'), ('exhibition', 'Exhibition / Expo'), ('charity', 'Charity / Fundraiser'), ('party', 'Party / Social'), ('reunion', 'Reunion'), ('religious', 'Religious / Faith'), ('product_launch', 'Product Launch'), ('sale', 'Sale / Promo'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='EventFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('going', 'Going')], default='interested', max_length=12)),
                ('notify', models.BooleanField(default=True, help_text='Receive notifications about this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='social.socialevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventFollow_Table',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('event_updated', 'Event updated'), ('event_reminder', 'Event reminder'), ('event_cancelled', 'Event cancelled'), ('new_comment', 'New comment')], db_index=True, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.socialevent')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventNotification_Table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'is_read'], name='EventNotifi_to_user_751b13_idx'), models.Index(fields=['event', 'notif_type'], name='EventNotifi_event_i_b2890d_idx')],
            },
        ),
    ]
