# Generated by Django 5.2.6 on 2025-12-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_rename_file_url_channelmessage_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmessage',
            old_name='channemessage_id',
            new_name='channelmessage_id',
        ),
    ]
