# Generated by Django 5.2.6 on 2026-08-31 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_businesspage_admins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_business', models.BooleanField(default=False)),
                ('conversation', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='business_message_files/')),
                ('linked_product_snapshot', models.JSONField(blank=True, null=True)),
                ('linked_job_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to='social.businesspage')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_message_threads', to=settings.AUTH_USER_MODEL)),
                ('linked_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_enquiry_messages', to='social.jobvacancy')),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_enquiry_messages', to='social.market')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social.businessmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_business_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['business_page', 'customer', '-created_at'], name='bizmsg_page_cust_idx'), models.Index(fields=['business_page', '-created_at'], name='bizmsg_page_created_idx'), models.Index(fields=['business_page', 'is_from_business', 'is_read'], name='bizmsg_page_unread_idx')],
            },
        ),
    ]
