# Generated by Django 5.2.6 on 2025-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_rename_channemessage_id_channelmessage_channelmessage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_file'),
        ),
    ]
