# Generated by Django 5.2.6 on 2026-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_socialevent_capacity_socialevent_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/'),
        ),
    ]
