# Generated by Django 5.2.6 on 2026-09-13 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_businessmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspostcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesspostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.businesspostcomment'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.eventcomment'),
        ),
        migrations.AddField(
            model_name='jobcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.jobcomment'),
        ),
        migrations.AddField(
            model_name='profileachievementcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileachievementcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.profileachievementcomment'),
        ),
        migrations.AddField(
            model_name='profileeducationcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileeducationcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.profileeducationcomment'),
        ),
        migrations.AddField(
            model_name='profileexperiencecomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileexperiencecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.profileexperiencecomment'),
        ),
        migrations.AddField(
            model_name='profileportfolioitemcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileportfolioitemcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.profileportfolioitemcomment'),
        ),
        migrations.AddField(
            model_name='profilepostcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilepostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.profilepostcomment'),
        ),
        migrations.AddField(
            model_name='profileservicecomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileservicecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.profileservicecomment'),
        ),
        migrations.AlterField(
            model_name='profileitemnotification',
            name='notif_type',
            field=models.CharField(choices=[('new_vibe', 'New reaction'), ('new_comment', 'New comment'), ('new_reply', 'New reply'), ('mention', 'Mention')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profilepostnotification',
            name='notif_type',
            field=models.CharField(choices=[('new_vibe', 'New reaction'), ('new_comment', 'New comment'), ('new_reply', 'New reply'), ('mention', 'Mention')], db_index=True, max_length=20),
        ),
    ]
