# Generated by Django 5.2.6 on 2026-08-04 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_profile_cover_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessnotification',
            name='notif_type',
            field=models.CharField(choices=[('new_follower', 'New page follower'), ('new_product', 'New product'), ('new_comment', 'New comment on a post')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessPost',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text update'), ('poll', 'Poll')], db_index=True, default='text', max_length=10)),
                ('caption', models.TextField(blank=True, default='')),
                ('video', models.FileField(blank=True, null=True, upload_to='business_post_videos/')),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.businesspage')),
            ],
            options={
                'db_table': 'BusinessPost_Table',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='businessnotification',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Set for new_comment notifications only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='social.businesspost'),
        ),
        migrations.CreateModel(
            name='BusinessPostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.businesspost')),
            ],
            options={
                'db_table': 'BusinessPostComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPostImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.businesspost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPostPoll',
            fields=[
                ('poll_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Let voters pick more than one option.')),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='social.businesspost')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPostPollOption',
            fields=[
                ('option_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='social.businesspostpoll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPostPollVote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.businesspostpolloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('option', 'user'), name='unique_vote_per_option_per_user')],
            },
        ),
        migrations.CreateModel(
            name='BusinessPostVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.businesspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_post_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BusinessPostVibe_Table',
                'ordering': ['created_at'],
                'unique_together': {('post', 'user')},
            },
        ),
    ]
