# Generated by Django 5.2.6 on 2025-12-23 11:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='channelMessage_files'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='audio_message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='logo_iowyea', max_length=255, verbose_name='picture'),
        ),
    ]
