# Generated by Django 5.2.6 on 2026-08-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_alter_businessnotification_notif_type_businesspost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_type',
            field=models.CharField(blank=True, choices=[('skilled_professional', 'Skilled Professional'), ('job_seeker', 'Job Seeker'), ('business_owner', 'Business Owner'), ('teacher_tutor', 'Teacher / Tutor'), ('freelancer', 'Freelancer'), ('artisan_technician', 'Artisan / Technician'), ('service_provider', 'Service Provider'), ('student_apprentice', 'Student / Apprentice'), ('employer_recruiter', 'Employer / Recruiter'), ('other_professional', 'Other Professional')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_type_cv',
            field=models.FileField(blank=True, null=True, upload_to='member_type/cv/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_type_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
