# Generated by Django 5.2.6 on 2025-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='post_file'),
        ),
    ]
