# Generated by Django 5.2.6 on 2025-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_post_view_alter_channelmessage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_file'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to='message_file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='post_file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, upload_to='post_file'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='file',
            field=models.FileField(blank=True, upload_to='comment_file'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='male.png', upload_to='profile_image/'),
        ),
    ]
