# Generated by Django 5.2.6 on 2026-08-09 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_profile_member_type_profile_member_type_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspage',
            name='enabled_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='page_type',
            field=models.CharField(choices=[('business', 'Business Owner'), ('freelancer', 'Freelancer'), ('developer', 'Developer / Tech Professional'), ('teacher', 'Teacher / Tutor'), ('artisan', 'Artisan / Technician'), ('service_provider', 'Service Provider'), ('creative', 'Creative / Artist'), ('student', 'Student'), ('skilled_professional', 'Skilled Professional'), ('other', 'Other Professional')], db_index=True, default='business', max_length=25),
        ),
        migrations.AddField(
            model_name='businesspage',
            name='sells_products',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesspost',
            name='post_category',
            field=models.CharField(choices=[('update', 'General Update'), ('work', 'Work Update'), ('project', 'Project'), ('tutorial', 'Tutorial'), ('announcement', 'Announcement')], db_index=True, default='update', max_length=15),
        ),
        migrations.CreateModel(
            name='BusinessAchievement',
            fields=[
                ('achievement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('issuer', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('date_achieved', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_achievement_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='social.businesspage')),
            ],
            options={
                'db_table': 'BusinessAchievement_Table',
                'ordering': ['order', '-date_achieved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPortfolioItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('portfolio', 'Portfolio piece'), ('project', 'Project')], db_index=True, default='portfolio', max_length=12)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('link_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_ongoing', models.BooleanField(default=False, help_text='Only meaningful for projects.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_portfolio_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='social.businesspage')),
            ],
            options={
                'db_table': 'BusinessPortfolioItem_Table',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('price_text', models.CharField(blank=True, default='', help_text='e.g. ₦15,000, Starting from ₦5,000/hr, or Negotiable', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_service_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='social.businesspage')),
            ],
            options={
                'db_table': 'BusinessService_Table',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
