# Generated by Django 5.2.6 on 2026-08-09 19:17

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_businesspage_enabled_sections_businesspage_page_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_type_cv_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_type_cv',
            field=models.FileField(blank=True, null=True, upload_to='member_type/cv/', validators=[social.models.validate_cv_extension]),
        ),
    ]
