# Generated by Django 5.2.6 on 2025-12-26 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnails'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
