# Generated by Django 5.2.6 on 2026-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_profile_member_type_cv_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
