# Generated by Django 5.2.6 on 2026-08-13 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessachievement',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='social.profile'),
        ),
        migrations.AddField(
            model_name='businessportfolioitem',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='social.profile'),
        ),
        migrations.AddField(
            model_name='businesspost',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_posts', to='social.profile'),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='social.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='enabled_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='sells_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessachievement',
            name='business_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='social.businesspage'),
        ),
        migrations.AlterField(
            model_name='businessportfolioitem',
            name='business_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='social.businesspage'),
        ),
        migrations.AlterField(
            model_name='businesspost',
            name='business_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.businesspage'),
        ),
        migrations.AlterField(
            model_name='businessservice',
            name='business_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='social.businesspage'),
        ),
    ]
