# Generated by Django 5.2.6 on 2025-12-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_profile_last_seen_profile_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
