# Generated by Django 5.2.6 on 2026-01-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_channeluserlastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social.channelmessage'),
        ),
    ]
