# Generated by Django 5.2.6 on 2026-01-13 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_channelmessage_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AddField(
            model_name='channel',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_from_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_broadcast_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='subscribed_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
