# Generated by Django 5.2.6 on 2026-01-13 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0031_alter_channel_options_channel_blocked_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_of_channel', to=settings.AUTH_USER_MODEL),
        ),
    ]
