# Generated by Django 5.2.6 on 2026-01-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0032_channel_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
