# Generated by Django 5.2.6 on 2026-01-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_post_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='product_condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used - Like New'), ('Fair', 'Used - Fair Condition')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='market',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
