# Generated by Django 5.2.6 on 2026-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_market_is_promoted_market_product_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
