# Generated by Django 5.2.6 on 2026-02-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0036_profile_website_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
