# Generated by Django 5.2.6 on 2026-02-03 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0039_privacysetting_profileshare_followrequest_userblock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacysetting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profileshare',
            name='profile_shared',
        ),
        migrations.RemoveField(
            model_name='profileshare',
            name='sharer',
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='blocked_user',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='blocker',
        ),
        migrations.AlterUniqueTogether(
            name='userreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='reported_user',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='reporter',
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('story_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], default='text', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='stories/videos/')),
                ('background_color', models.CharField(blank=True, default='#0095f6', max_length=7)),
                ('text_color', models.CharField(blank=True, default='#ffffff', max_length=7)),
                ('font_size', models.IntegerField(default=24)),
                ('font_family', models.CharField(blank=True, default='Arial', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewed_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
        migrations.DeleteModel(
            name='PrivacySetting',
        ),
        migrations.DeleteModel(
            name='ProfileShare',
        ),
        migrations.DeleteModel(
            name='UserBlock',
        ),
        migrations.DeleteModel(
            name='UserReport',
        ),
    ]
