# Generated by Django 5.2.6 on 2026-02-11 06:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0040_remove_privacysetting_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='channelMessage_files'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='message_file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='logo_iowyea', max_length=255, verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
