# Generated by Django 5.2.6 on 2026-02-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0041_remove_profile_last_seen_alter_channelmessage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_file'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='post_file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, upload_to='post_file'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='file',
            field=models.FileField(blank=True, upload_to='comment_file'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='male.png', upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories/videos/'),
        ),
    ]
