# Generated by Django 5.2.6 on 2026-02-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0044_remove_post_co_authors_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='parent_reply',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
