# Generated by Django 5.2.6 on 2026-03-04 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0048_blockeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
