# Generated by Django 5.2.6 on 2026-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0050_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link_preview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
