# Generated by Django 5.2.6 on 2026-03-14 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0051_message_link_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mention_notifications', to='social.postcomment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('comment', 'Comment'), ('repost', 'Repost'), ('mention', 'Mention')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='social_noti_recipie_54eb87_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='social_noti_recipie_dbb77a_idx'),
        ),
    ]
