# Generated by Django 5.2.6 on 2026-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0052_notification_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_preview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
