# Generated by Django 5.2.6 on 2026-03-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0053_post_link_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Everyone'), ('followers_only', 'Followers only'), ('private', 'Nobody (Hidden)')], db_index=True, default='public', help_text='Controls who can view this profile details', max_length=20),
        ),
    ]
