# Generated by Django 5.2.6 on 2026-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0054_profile_privacy_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=254)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('succeeded', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LoginAttempt_Table',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['username', 'attempted_at'], name='login_attempt_user_time_idx')],
            },
        ),
    ]
