# Generated by Django 5.2.6 on 2026-03-16 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0056_postvibe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at'], name='post_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_repost', 'created_at'], name='post_repost_created_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['author', 'created_at'], name='postcomment_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='postvibe',
            index=models.Index(fields=['user', 'created_at'], name='postvibe_user_created_idx'),
        ),
    ]
