# Generated by Django 5.2.6 on 2026-03-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0057_post_post_author_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvibe',
            name='vibe_type',
            field=models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10),
        ),
    ]
