# Generated by Django 5.2.6 on 2026-03-20 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0059_userfeedprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedprofile',
            name='last_feed_visit',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last time this user loaded the home feed. Used by the feed algorithm to surface missed posts.', null=True),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocker'], name='blockeduser_blocker_idx'),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocked'], name='blockeduser_blocked_idx'),
        ),
    ]
