# Generated by Django 5.2.6 on 2026-03-23 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0060_userfeedprofile_last_feed_visit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('school', 'What primary school did you attend?'), ('city', 'In what city were you born?'), ('mother', "What is your mother's maiden name?"), ('friend', 'What is the name of your childhood best friend?'), ('car', 'What was the make of your first car?'), ('street', 'What street did you grow up on?'), ('nickname', 'What nickname did your family call you as a child?')], max_length=20)),
                ('answer_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secret_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SecretQuestion_Table',
            },
        ),
    ]
