# Generated by Django 5.2.6 on 2026-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0061_secretquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='ad_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
