# Generated by Django 5.2.6 on 2026-03-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0063_channelmessage_link_preview_channelmessagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_messages', to='social.market'),
        ),
        migrations.AddField(
            model_name='message',
            name='linked_product_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
