# Generated by Django 5.2.6 on 2026-03-28 07:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0064_message_linked_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='channelMessage_files'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='message_file'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('comment', 'Comment'), ('repost', 'Repost'), ('mention', 'Mention'), ('reply', 'Reply')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='logo_iowyea', max_length=255, verbose_name='picture'),
        ),
    ]
