# Generated by Django 5.2.6 on 2026-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0067_profile_date_of_birth_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_dob',
            field=models.BooleanField(default=False, help_text='Show date of birth on public profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_gender',
            field=models.BooleanField(default=True, help_text='Show gender on public profile'),
        ),
    ]
