# Generated by Django 5.2.6 on 2026-04-05 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0068_profile_show_dob_profile_show_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('town', 'Town Meeting'), ('festival', 'Festival'), ('wedding', 'Wedding'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SocialEvent_Table',
                'ordering': ['date', 'time'],
            },
        ),
    ]
