# Generated by Django 5.2.6 on 2026-04-05 08:07

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0069_socialevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('gig', 'Gig'), ('fulltime', 'Full-time'), ('apprenticeship', 'Apprenticeship')], db_index=True, default='fulltime', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, default='')),
                ('contact_info', models.CharField(blank=True, default='', help_text='Email, phone, or link to apply', max_length=300)),
                ('salary_range', models.CharField(blank=True, default='', help_text='e.g. ₦80,000–₦120,000/month or "Negotiable"', max_length=100)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'JobVacancy_Table',
                'ordering': ['-created_at'],
            },
        ),
    ]
