# Generated by Django 5.2.6 on 2026-04-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0070_jobvacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_covers/'),
        ),
    ]
