# Generated by Django 5.2.6 on 2026-04-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0071_alter_jobvacancy_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialevent',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/'),
        ),
    ]
