# Generated by Django 5.2.6 on 2026-04-06 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0072_socialevent_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.socialevent')),
            ],
            options={
                'db_table': 'EventComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_comments', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.jobvacancy')),
            ],
            options={
                'db_table': 'JobComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.market')),
            ],
            options={
                'db_table': 'MarketComment_Table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.socialevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventVibe_Table',
                'ordering': ['created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='JobVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.jobvacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'JobVibe_Table',
                'ordering': ['created_at'],
                'unique_together': {('job', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MarketVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_type', models.CharField(choices=[('fire', '🔥 Fire'), ('real', '💯 Real'), ('vibing', '🎵 Vibing'), ('dead', '😂 Dead'), ('cringe', '😬 Cringe'), ('chill', '🧊 Chill'), ('love', '❤️ Love')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='social.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MarketVibe_Table',
                'ordering': ['created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
