# Generated by Django 5.2.6 on 2026-04-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0073_eventcomment_jobcomment_marketcomment_eventvibe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='community_area',
            field=models.CharField(blank=True, choices=[('ajangba', 'Ajangba Community'), ('ajana', 'Ajana Community'), ('atipa', 'Atipa Community'), ('agede', 'Agede Community'), ('ehinke', 'Ehinke Community'), ('mapo', 'Mapo Community'), ('koso', 'Koso Community'), ('oke_tege', 'Oke Tege Community'), ('laha', 'Laha Community'), ('ojupopo', 'Ojupopo Community'), ('isale_odo', 'Isale Odo Community'), ('fulani', 'Fulani Community')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='family_house',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='residency_status',
            field=models.CharField(blank=True, choices=[('resident', 'Living in Kishi'), ('diaspora', 'Living Outside / Diaspora')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_school',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
